// export const locker_1 = [1, 2, 3]
// export const locker_2 = [4, 5, 6]
// export const locker_3 = [7, 8, 9]
// export const locker_4 = [10, 11, 12]
export const locker_1 = [1]
export const locker_2 = [2]
export const locker_3 = [3]
export const locker_4 = [4]
export const locker_5 = [5]
export const locker_6 = [6]
export const locker_7 = [7]
export const locker_8 = [8]
export const locker_9 = [9]
export const locker_10 = [10]
export const locker_11 = [11]
export const locker_12 = [12]

